import { StyleSheet } from "react-native";
import { Colors, Fonts, Responsive } from "@/theme";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: Colors.appColors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
    backgroundColor: Colors.appColors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.opacityColors.blackOpacity4,
  },
  logoContainer: {
    // flexDirection: "row",
    // alignItems: "center",
    // gap: Responsive.widthPercentageToDP(2),
  },
  logoIcon: {
    width: Responsive.widthPercentageToDP(6.4),
    height: Responsive.heightPercentageToDP(3),
  },
  logoText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
    letterSpacing: -0.2,
  },
  avatar: {
    width: Responsive.widthPercentageToDP(9.6),
    height: Responsive.widthPercentageToDP(9.6),
    borderRadius: Responsive.widthPercentageToDP(4.8),
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity10,
  },
  scrollContent: {
    paddingBottom: Responsive.heightPercentageToDP(16),
  },
  heroSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
  },
  heroTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(32),
    color: Colors.appColors.secondary,
    letterSpacing: -0.8,
  },
  heroSubtitle: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(16),
    color: Colors.appColors.tertiary,
    marginTop: 4,
  },
  searchSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(1),
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(4),
    height: 52,
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity10,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  searchIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.appColors.tertiary,
  },
  searchInput: {
    flex: 1,
    fontFamily: Fonts.regular,
    color: Colors.appColors.secondary,
    fontSize: Responsive.convertFontScale(15),
    paddingLeft: Responsive.widthPercentageToDP(2),
  },
  searchRightIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchDivider: {
    width: 1,
    height: 20,
    backgroundColor: Colors.appColors.borderLight,
    marginHorizontal: Responsive.widthPercentageToDP(2),
  },
  searchBtn: {
    padding: 6,
  },
  searchRightIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.appColors.tertiary,
  },
  tabsSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(2),
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: Colors.appColors.grayLight,
    padding: 4,
    borderRadius: 14,
    position: "relative",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    height: 38,
  },
  tabButtonText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    textAlign: "center",
  },
  tabIndicator: {
    position: "absolute",
    top: 4,
    bottom: 4,
    borderRadius: 10,
    backgroundColor: Colors.appColors.primary,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  filtersSection: {
    marginTop: Responsive.heightPercentageToDP(2),
  },
  filtersContent: {
    paddingLeft: Responsive.widthPercentageToDP(5.3),
    paddingRight: Responsive.widthPercentageToDP(5.3),
    gap: Responsive.widthPercentageToDP(2),
  },
  filterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: Colors.appColors.white,
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    borderRadius: 20,
  },
  filterPillActive: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: Colors.appColors.primary,
  },
  filterIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.appColors.primary,
  },
  filterPillText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  filterPillTextActive: {
    color: Colors.appColors.primary,
    fontFamily: Fonts.semiBold,
  },
  listHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(3),
  },
  listCountText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.tertiary,
  },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  sortIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.appColors.tertiary,
  },
  sortText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.tertiary,
  },
  cardsContainer: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    gap: 16,
    marginTop: 12,
  },
  card: {
    backgroundColor: Colors.appColors.white,
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity4,
    borderRadius: 16,
    padding: 20,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  cardLogoContainer: {
    width: 56,
    height: 56,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity4,
    overflow: "hidden",
  },
  cardLogo: {
    width: 40,
    height: 40,
  },
  cardLogoText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(24),
    color: Colors.appColors.white,
  },
  cardTitleContainer: {
    flex: 1,
    paddingTop: 2,
  },
  cardTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(18),
    color: Colors.appColors.secondary,
  },
  bookmarkBtn: {
    padding: 8,
    marginRight: -8,
    marginTop: -8,
  },
  bookmarkIcon: {
    width: 22,
    height: 22,
  },
  cardStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22c55e",
  },
  statusText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.appColors.grayMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  cardDescription: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.tertiary,
    lineHeight: 22,
    marginTop: 14,
  },
  cardTagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: Colors.appColors.grayLight,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
  },
  tagText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayDark,
  },
  specialTag: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: "rgba(255, 102, 0, 0.15)",
  },
  specialTagText: {
    color: Colors.appColors.primary,
    fontFamily: Fonts.semiBold,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: Colors.opacityColors.blackOpacity4,
    marginTop: 20,
    paddingTop: 16,
  },
  footerLeft: {
    flexDirection: "column",
    gap: 2,
  },
  footerStage: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.appColors.grayMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  footerValuation: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  viewDetailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginRight: -8,
  },
  viewDetailsText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.primary,
  },
  viewDetailsIcon: {
    width: 14,
    height: 14,
  },
  premiumOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: Responsive.heightPercentageToDP(38),
    justifyContent: "flex-start",
    alignItems: "center",
    zIndex: 100,
    overflow: "hidden",
  },
  premiumGlass: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  premiumCard: {
    backgroundColor: Colors.appColors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.appColors.borderPeach,
    padding: 24,
    width: "90%",
    marginTop: Responsive.heightPercentageToDP(8),
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 8,
    alignItems: "center",
  },
  lockIconBg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  lockIcon: {
    width: 26,
    height: 26,
  },
  premiumTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
    textAlign: "center",
    marginBottom: 8,
  },
  premiumSubtitle: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.tertiary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  premiumFeatures: {
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  premiumFeatureItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  premiumFeatureBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.appColors.primary,
  },
  premiumFeatureText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  premiumButton: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: "100%",
    alignItems: "center",
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  premiumButtonText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.white,
  },
  fab: {
    position: "absolute",
    bottom: 100,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.appColors.primary,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 28,
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
    zIndex: 90,
  },
  fabText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.white,
  },
  fabIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.appColors.white,
  },
  // Modal/Bottom Sheet Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(25, 28, 29, 0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: Colors.appColors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "90%",
  },
  modalHandle: {
    width: 48,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.appColors.grayLight,
    alignSelf: "center",
    marginTop: 12,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.opacityColors.blackOpacity4,
  },
  modalTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
  },
  resetBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  resetBtnText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.primary,
  },
  modalScroll: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 120,
  },
  modalSection: {
    marginBottom: 28,
  },
  modalSectionTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(12),
    color: Colors.appColors.tertiary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
  },
  dropdownTrigger: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Colors.appColors.grayLight,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
  },
  dropdownText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.secondary,
  },
  dropdownIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.appColors.tertiary,
  },
  dropdownOptions: {
    backgroundColor: Colors.appColors.grayLight,
    borderRadius: 12,
    marginTop: 4,
    overflow: "hidden",
  },
  dropdownOption: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.appColors.borderLight,
  },
  dropdownOptionText: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  dropdownOptionTextSelected: {
    fontFamily: Fonts.semiBold,
    color: Colors.appColors.primary,
  },
  checkboxGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  checkboxItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    width: "48%",
    backgroundColor: Colors.appColors.grayLight,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "transparent",
  },
  checkboxItemActive: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: Colors.appColors.primary,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: Colors.appColors.bookmarkInactive,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxBoxActive: {
    borderColor: Colors.appColors.primary,
    backgroundColor: Colors.appColors.primary,
  },
  checkMark: {
    color: Colors.appColors.white,
    fontSize: 11,
    fontWeight: "900",
  },
  checkboxText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  toggleLabel: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.secondary,
  },
  toggleSwitch: {
    width: 48,
    height: 26,
    borderRadius: 13,
    backgroundColor: Colors.appColors.grayLight,
    padding: 2,
    justifyContent: "center",
  },
  toggleSwitchActive: {
    backgroundColor: Colors.appColors.primary,
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.appColors.white,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sliderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sliderHeaderText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  sliderHeaderRange: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.primary,
  },
  sliderTrackContainer: {
    height: 24,
    justifyContent: "center",
    position: "relative",
  },
  sliderTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.appColors.grayLight,
    position: "relative",
    justifyContent: "center",
  },
  sliderProgress: {
    position: "absolute",
    height: 4,
    backgroundColor: Colors.appColors.primary,
  },
  sliderThumb: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.appColors.white,
    borderWidth: 2,
    borderColor: Colors.appColors.primary,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  modalFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderTopWidth: 1,
    borderTopColor: Colors.opacityColors.blackOpacity4,
  },
  applyButton: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: 16,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  applyButtonText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(16),
    color: Colors.appColors.white,
  },
});

export default styles;
