import { StyleSheet } from "react-native";
import { Colors, Fonts, Responsive } from "@/theme";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: Colors.appColors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
    backgroundColor: Colors.appColors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.opacityColors.blackOpacity4,
  },
  headerLeft: {
    alignItems: "center",
  },
  avatar: {
    width: Responsive.widthPercentageToDP(10.7),
    height: Responsive.heightPercentageToDP(5),
    borderRadius: Responsive.widthPercentageToDP(5.3),
  },
  headerTexts: {
    justifyContent: "center",
  },
  greetingText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayDark,
    letterSpacing: 0.3,
  },
  appTitleText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.primary,
    letterSpacing: -0.2,
  },
  notificationButton: {
    width: Responsive.widthPercentageToDP(10.7),
    height: Responsive.heightPercentageToDP(5),
    borderRadius: Responsive.widthPercentageToDP(5.3),
    backgroundColor: Colors.appColors.grayLight,
    justifyContent: "center",
    alignItems: "center",
  },
  bellIcon: {
    width: Responsive.widthPercentageToDP(5.3),
    height: Responsive.heightPercentageToDP(2.5),
  },
  notificationBadge: {
    position: "absolute",
    top: Responsive.heightPercentageToDP(1.25),
    right: Responsive.widthPercentageToDP(2.9),
    width: Responsive.widthPercentageToDP(2.1),
    height: Responsive.heightPercentageToDP(1),
    borderRadius: Responsive.widthPercentageToDP(1.1),
    backgroundColor: Colors.appColors.primary,
    borderWidth: 1.5,
    borderColor: Colors.appColors.white,
  },
  scrollContent: {
    paddingBottom: Responsive.heightPercentageToDP(15),
  },
  searchSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(2),
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(7.5),
    height: Responsive.heightPercentageToDP(6),
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    // Shadow
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.02,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 2,
  },
  searchIcon: {
    tintColor: Colors.appColors.tertiary,
    width: Responsive.widthPercentageToDP(5),
    height: Responsive.heightPercentageToDP(2),
    marginRight: Responsive.widthPercentageToDP(2),
  },
  searchInput: {
    flex: 1,
    fontFamily: Fonts.regular,
    color: Colors.appColors.secondary,
    fontSize: Responsive.convertFontScale(14),
  },
  countrySection: {
    marginTop: Responsive.heightPercentageToDP(3.5),
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
  },
  countryTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(18),
    color: Colors.appColors.secondary,
    marginBottom: Responsive.heightPercentageToDP(1.5),
    marginTop: Responsive.heightPercentageToDP(1.5),
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
  },

  sectionContainer: {
    marginTop: Responsive.heightPercentageToDP(3.5),
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Responsive.heightPercentageToDP(3.5),
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
  },
  sectionTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(18),
    color: Colors.appColors.secondary,
    marginBottom: Responsive.heightPercentageToDP(1.5),
  },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.1),
    marginBottom: Responsive.heightPercentageToDP(1.5),
  },
  viewAllText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.primary,
  },
  arrowIcon: {
    width: Responsive.widthPercentageToDP(3.7),
    height: Responsive.heightPercentageToDP(1.75),
  },
  horizontalScrollContent: {
    paddingLeft: Responsive.widthPercentageToDP(5.3),
    paddingRight: Responsive.widthPercentageToDP(5.3),
    gap: Responsive.widthPercentageToDP(4.3),
  },
  startupCard: {
    width: Responsive.widthPercentageToDP(74.7),
    height: Responsive.heightPercentageToDP(26.3),
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(5.3),
    padding: Responsive.widthPercentageToDP(5.3),
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    justifyContent: "space-between",
    // Shadow
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.05,
    shadowRadius: Responsive.widthPercentageToDP(3.2),
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(3.2),
    flex: 1,
  },
  logoContainer: {
    width: Responsive.widthPercentageToDP(11.7),
    height: Responsive.heightPercentageToDP(5.5),
    borderRadius: Responsive.widthPercentageToDP(2.7),
    justifyContent: "center",
    alignItems: "center",
  },
  logoText: {
    color: Colors.appColors.white,
    fontSize: Responsive.convertFontScale(18),
    fontFamily: Fonts.bold,
  },
  cardTitleInfo: {
    flex: 1,
  },
  startupName: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.secondary,
    lineHeight: Responsive.convertFontScale(18),
  },
  startupMeta: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayMuted,
    marginTop: Responsive.heightPercentageToDP(0.25),
  },
  bookmarkIcon: {
    width: Responsive.widthPercentageToDP(4.8),
    height: Responsive.heightPercentageToDP(2.25),
  },
  startupDesc: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.grayDark,
    lineHeight: Responsive.convertFontScale(18),
    marginTop: Responsive.heightPercentageToDP(1.25),
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Responsive.heightPercentageToDP(1.5),
  },
  categoryBadge: {
    backgroundColor: Colors.appColors.grayLight,
    borderRadius: Responsive.widthPercentageToDP(2.1),
    paddingHorizontal: Responsive.widthPercentageToDP(2.7),
    paddingVertical: Responsive.heightPercentageToDP(0.5),
  },
  categoryBadgeText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayMuted,
  },
  cardArrowBtn: {
    width: Responsive.widthPercentageToDP(7.5),
    height: Responsive.heightPercentageToDP(3.5),
    borderRadius: Responsive.widthPercentageToDP(3.7),
    backgroundColor: Colors.appColors.grayLight,
    justifyContent: "center",
    alignItems: "center",
  },
  footerArrowIcon: {
    width: Responsive.widthPercentageToDP(3.7),
    height: Responsive.heightPercentageToDP(1.75),
  },
  heroSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(3.5),
  },
  heroGradientBg: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: Responsive.widthPercentageToDP(6.4),
    padding: Responsive.widthPercentageToDP(6.4),
    gap: Responsive.widthPercentageToDP(5.3),
    // Shadow
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(1.25) },
    shadowOpacity: 0.15,
    shadowRadius: Responsive.widthPercentageToDP(5.3),
    elevation: 8,
  },
  heroTextContainer: {
    gap: Responsive.heightPercentageToDP(0.5),
  },
  heroLabel: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.opacityColors.whiteOpacity80,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(24),
    color: Colors.appColors.white,
  },
  heroStatsContainer: {
    flexDirection: "row",
    gap: Responsive.widthPercentageToDP(2.7),
  },
  heroStatBadge: {
    flex: 1,
    backgroundColor: Colors.opacityColors.whiteOpacity20,
    borderRadius: Responsive.widthPercentageToDP(3.2),
    paddingVertical: Responsive.heightPercentageToDP(1.25),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.opacityColors.whiteOpacity10,
  },
  heroStatValue: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(18),
    color: Colors.appColors.white,
  },
  heroStatLabel: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.opacityColors.whiteOpacity80,
    marginTop: Responsive.heightPercentageToDP(0.25),
  },
  heroExploreBtn: {
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(4.8),
    height: Responsive.heightPercentageToDP(6.5),
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.05,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 2,
    alignSelf: "flex-start",
    paddingHorizontal: Responsive.widthPercentageToDP(6.4),
  },
  heroExploreBtnText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.primary,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Responsive.widthPercentageToDP(3.2),
    marginTop: Responsive.heightPercentageToDP(1),
  },
  statCard: {
    width: Responsive.widthPercentageToDP(42),
    flexGrow: 1,
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(5.3),
    padding: Responsive.widthPercentageToDP(4),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    marginBottom: Responsive.heightPercentageToDP(2),
    marginRight: Responsive.widthPercentageToDP(3.2),
    // Shadow
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.03,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 2,
  },
  statIcon: {
    width: Responsive.widthPercentageToDP(7.5),
    height: Responsive.heightPercentageToDP(3.5),
  },
  statCount: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(22),
    color: Colors.appColors.secondary,
    marginTop: Responsive.heightPercentageToDP(1),
  },
  statLabel: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayMuted,
    marginTop: Responsive.heightPercentageToDP(0.25),
  },
  horizontalPillsContent: {
    gap: Responsive.widthPercentageToDP(2.7),
    paddingRight: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(0.5),
    paddingLeft: Responsive.widthPercentageToDP(5.3),
  },
  pillButton: {
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    paddingVertical: Responsive.heightPercentageToDP(1.25),
    borderRadius: Responsive.widthPercentageToDP(4.8),
    justifyContent: "center",
    alignItems: "center",
  },
  pillButtonActive: {
    backgroundColor: Colors.appColors.primary,
  },
  pillButtonInactive: {
    backgroundColor: Colors.appColors.grayLight,
  },
  pillButtonText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
  },
  pillButtonTextActive: {
    color: Colors.appColors.white,
  },
  pillButtonTextInactive: {
    color: Colors.appColors.secondary,
  },
  industriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Responsive.widthPercentageToDP(3.2),
    marginTop: Responsive.heightPercentageToDP(1),
  },
  industryCard: {
    width: Responsive.widthPercentageToDP(43),
    flexGrow: 1,
    flexDirection: "row",
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(4.8),
    padding: Responsive.widthPercentageToDP(3.7),
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(2.7),
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    marginRight: Responsive.widthPercentageToDP(2),
    marginBottom: Responsive.heightPercentageToDP(1),
    // Shadow
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.03,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 2,
  },
  industryEmoji: {
    fontSize: Responsive.convertFontScale(24),
  },
  industryInfo: {
    flex: 1,
    justifyContent: "center",
  },
  industryName: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  industryCount: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.appColors.grayMuted,
    marginTop: Responsive.heightPercentageToDP(0.25),
  },
  seeMoreBtn: {
    flexDirection: "row",
    backgroundColor: Colors.appColors.grayLight,
    height: Responsive.heightPercentageToDP(6.5),
    borderRadius: Responsive.widthPercentageToDP(4.8),
    justifyContent: "center",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(2.1),
    marginTop: Responsive.heightPercentageToDP(2),
  },
  seeMoreBtnText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  seeMoreArrowIcon: {
    width: Responsive.widthPercentageToDP(3.7),
    height: Responsive.heightPercentageToDP(1.75),
  },
});

export default styles;
