import { StyleSheet } from "react-native";
import { Colors, Fonts, Responsive } from "@/theme";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: Colors.appColors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
    backgroundColor: Colors.appColors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.opacityColors.blackOpacity4,
  },
  logoContainer: {
    // Custom header logo styling if needed
  },
  logoIcon: {
    width: Responsive.widthPercentageToDP(6.4),
    height: Responsive.heightPercentageToDP(3),
  },
  logoText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
    letterSpacing: -0.2,
  },
  avatar: {
    width: Responsive.widthPercentageToDP(9.6),
    height: Responsive.widthPercentageToDP(9.6),
    borderRadius: Responsive.widthPercentageToDP(4.8),
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity10,
  },
  scrollContent: {
    paddingBottom: Responsive.heightPercentageToDP(16),
  },
  heroSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
  },
  heroTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(32),
    color: Colors.appColors.secondary,
    letterSpacing: -0.8,
  },
  heroSubtitle: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(16),
    color: Colors.appColors.tertiary,
    marginTop: Responsive.heightPercentageToDP(0.5),
  },
  searchSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(1),
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(4),
    height: Responsive.heightPercentageToDP(6.2),
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity10,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.25) },
    shadowOpacity: 0.02,
    shadowRadius: Responsive.widthPercentageToDP(1.1),
    elevation: 1,
  },
  searchIcon: {
    width: Responsive.widthPercentageToDP(5.3),
    height: Responsive.heightPercentageToDP(2.5),
    tintColor: Colors.appColors.tertiary,
  },
  searchInput: {
    flex: 1,
    fontFamily: Fonts.regular,
    color: Colors.appColors.secondary,
    fontSize: Responsive.convertFontScale(15),
    paddingLeft: Responsive.widthPercentageToDP(2),
  },
  searchRightIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchDivider: {
    width: 1,
    height: Responsive.heightPercentageToDP(2.5),
    backgroundColor: Colors.appColors.borderLight,
    marginHorizontal: Responsive.widthPercentageToDP(2),
  },
  searchBtn: {
    padding: Responsive.widthPercentageToDP(1.6),
  },
  searchRightIcon: {
    width: Responsive.widthPercentageToDP(5.3),
    height: Responsive.heightPercentageToDP(2.5),
    tintColor: Colors.appColors.tertiary,
  },
  tabsSection: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(2),
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: Colors.appColors.grayLight,
    padding: Responsive.widthPercentageToDP(1.1),
    borderRadius: Responsive.widthPercentageToDP(3.7),
    position: "relative",
  },
  tabButton: {
    flex: 1,
    paddingVertical: Responsive.heightPercentageToDP(1.2),
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    height: Responsive.heightPercentageToDP(4.75),
  },
  tabButtonText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    textAlign: "center",
  },
  tabIndicator: {
    position: "absolute",
    top: Responsive.heightPercentageToDP(0.5),
    bottom: Responsive.heightPercentageToDP(0.5),
    borderRadius: Responsive.widthPercentageToDP(2.7),
    backgroundColor: Colors.appColors.primary,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.25) },
    shadowOpacity: 0.1,
    shadowRadius: Responsive.widthPercentageToDP(0.8),
    elevation: 2,
  },
  filtersSection: {
    marginTop: Responsive.heightPercentageToDP(2),
  },
  filtersContent: {
    paddingLeft: Responsive.widthPercentageToDP(5.3),
    paddingRight: Responsive.widthPercentageToDP(5.3),
    gap: Responsive.widthPercentageToDP(2),
  },
  filterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.6),
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    paddingVertical: Responsive.heightPercentageToDP(1),
    backgroundColor: Colors.appColors.white,
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    borderRadius: Responsive.widthPercentageToDP(5.3),
  },
  filterPillActive: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: Colors.appColors.primary,
  },
  filterIcon: {
    width: Responsive.widthPercentageToDP(3.7),
    height: Responsive.heightPercentageToDP(1.75),
    tintColor: Colors.appColors.primary,
  },
  filterPillText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  filterPillTextActive: {
    color: Colors.appColors.primary,
    fontFamily: Fonts.semiBold,
  },
  listHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    marginTop: Responsive.heightPercentageToDP(3),
  },
  listCountText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.tertiary,
  },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.1),
  },
  sortIcon: {
    width: Responsive.widthPercentageToDP(4.3),
    height: Responsive.heightPercentageToDP(2),
    tintColor: Colors.appColors.tertiary,
  },
  sortText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.tertiary,
  },
  cardsContainer: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    gap: Responsive.heightPercentageToDP(2),
    marginTop: Responsive.heightPercentageToDP(1.5),
  },
  card: {
    backgroundColor: Colors.appColors.white,
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity4,
    borderRadius: Responsive.widthPercentageToDP(4.3),
    padding: Responsive.widthPercentageToDP(5.3),
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.02,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: Responsive.widthPercentageToDP(3.2),
  },
  cardLogoContainer: {
    width: Responsive.widthPercentageToDP(15),
    height: Responsive.widthPercentageToDP(15),
    borderRadius: Responsive.widthPercentageToDP(3.7),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.opacityColors.blackOpacity4,
    overflow: "hidden",
  },
  cardLogo: {
    width: Responsive.widthPercentageToDP(10.7),
    height: Responsive.widthPercentageToDP(10.7),
  },
  cardLogoText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(24),
    color: Colors.appColors.white,
  },
  cardTitleContainer: {
    flex: 1,
    paddingTop: Responsive.heightPercentageToDP(0.25),
  },
  cardTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(18),
    color: Colors.appColors.secondary,
  },
  bookmarkBtn: {
    padding: Responsive.widthPercentageToDP(2.1),
    marginRight: -Responsive.widthPercentageToDP(2.1),
    marginTop: -Responsive.widthPercentageToDP(2.1),
  },
  bookmarkIcon: {
    width: Responsive.widthPercentageToDP(5.8),
    height: Responsive.widthPercentageToDP(5.8),
  },
  cardStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.6),
    marginTop: Responsive.heightPercentageToDP(0.5),
  },
  statusDot: {
    width: Responsive.widthPercentageToDP(1.6),
    height: Responsive.widthPercentageToDP(1.6),
    borderRadius: Responsive.widthPercentageToDP(0.8),
    backgroundColor: "#22c55e",
  },
  statusText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.appColors.grayMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  cardDescription: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.tertiary,
    lineHeight: Responsive.convertFontScale(22),
    marginTop: Responsive.heightPercentageToDP(1.75),
  },
  cardTagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Responsive.widthPercentageToDP(2.1),
    marginTop: Responsive.heightPercentageToDP(2),
  },
  tag: {
    paddingHorizontal: Responsive.widthPercentageToDP(2.7),
    paddingVertical: Responsive.heightPercentageToDP(0.75),
    backgroundColor: Colors.appColors.grayLight,
    borderRadius: Responsive.widthPercentageToDP(1.6),
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
  },
  tagText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.grayDark,
  },
  specialTag: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: "rgba(255, 102, 0, 0.15)",
  },
  specialTagText: {
    color: Colors.appColors.primary,
    fontFamily: Fonts.semiBold,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: Colors.opacityColors.blackOpacity4,
    marginTop: Responsive.heightPercentageToDP(2.5),
    paddingTop: Responsive.heightPercentageToDP(2),
  },
  footerLeft: {
    flexDirection: "column",
    gap: Responsive.heightPercentageToDP(0.25),
  },
  footerStage: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(10),
    color: Colors.appColors.grayMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  footerValuation: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  viewDetailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.1),
    paddingVertical: Responsive.heightPercentageToDP(0.75),
    paddingHorizontal: Responsive.widthPercentageToDP(2.1),
    marginRight: -Responsive.widthPercentageToDP(2.1),
  },
  viewDetailsText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.primary,
  },
  viewDetailsIcon: {
    width: Responsive.widthPercentageToDP(3.7),
    height: Responsive.heightPercentageToDP(1.75),
  },
  premiumOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: Responsive.heightPercentageToDP(38),
    justifyContent: "flex-start",
    alignItems: "center",
    zIndex: 100,
    overflow: "hidden",
  },
  premiumGlass: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  premiumCard: {
    backgroundColor: Colors.appColors.white,
    borderRadius: Responsive.widthPercentageToDP(5.3),
    borderWidth: 1,
    borderColor: Colors.appColors.borderPeach,
    padding: Responsive.widthPercentageToDP(6.4),
    width: "90%",
    marginTop: Responsive.heightPercentageToDP(8),
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(1.25) },
    shadowOpacity: 0.08,
    shadowRadius: Responsive.widthPercentageToDP(5.3),
    elevation: 8,
    alignItems: "center",
  },
  lockIconBg: {
    width: Responsive.widthPercentageToDP(15),
    height: Responsive.widthPercentageToDP(15),
    borderRadius: Responsive.widthPercentageToDP(7.5),
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Responsive.heightPercentageToDP(2),
  },
  lockIcon: {
    width: Responsive.widthPercentageToDP(7),
    height: Responsive.widthPercentageToDP(7),
  },
  premiumTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
    textAlign: "center",
    marginBottom: Responsive.heightPercentageToDP(1),
  },
  premiumSubtitle: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.tertiary,
    textAlign: "center",
    lineHeight: Responsive.convertFontScale(20),
    marginBottom: Responsive.heightPercentageToDP(2.5),
  },
  premiumFeatures: {
    width: "100%",
    gap: Responsive.heightPercentageToDP(1.5),
    marginBottom: Responsive.heightPercentageToDP(3),
  },
  premiumFeatureItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(2.1),
  },
  premiumFeatureBullet: {
    width: Responsive.widthPercentageToDP(1.6),
    height: Responsive.widthPercentageToDP(1.6),
    borderRadius: Responsive.widthPercentageToDP(0.8),
    backgroundColor: Colors.appColors.primary,
  },
  premiumFeatureText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
  },
  premiumButton: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: Responsive.widthPercentageToDP(6.4),
    paddingVertical: Responsive.heightPercentageToDP(1.75),
    paddingHorizontal: Responsive.widthPercentageToDP(8.5),
    width: "100%",
    alignItems: "center",
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.2,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 4,
  },
  premiumButtonText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.white,
  },
  fab: {
    position: "absolute",
    bottom: Responsive.heightPercentageToDP(12.5),
    right: Responsive.widthPercentageToDP(5.3),
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(1.6),
    backgroundColor: Colors.appColors.primary,
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(1.75),
    borderRadius: Responsive.widthPercentageToDP(7.5),
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.75) },
    shadowOpacity: 0.2,
    shadowRadius: Responsive.widthPercentageToDP(2.7),
    elevation: 6,
    zIndex: 90,
  },
  fabText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.white,
  },
  fabIcon: {
    width: Responsive.widthPercentageToDP(4.8),
    height: Responsive.heightPercentageToDP(2.25),
    tintColor: Colors.appColors.white,
  },
  // Modal/Bottom Sheet Styles are now located in src/components/FilterModal/styles.ts
});

export default styles;
