import { StyleSheet } from "react-native";
import { Colors, Fonts, Responsive } from "@/theme";

const styles = StyleSheet.create({
  // Modal/Bottom Sheet Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(25, 28, 29, 0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: Colors.appColors.white,
    borderTopLeftRadius: Responsive.widthPercentageToDP(8.5),
    borderTopRightRadius: Responsive.widthPercentageToDP(8.5),
    maxHeight: "90%",
  },
  modalHandle: {
    width: Responsive.widthPercentageToDP(12.8),
    height: Responsive.heightPercentageToDP(0.75),
    borderRadius: Responsive.widthPercentageToDP(0.8),
    backgroundColor: Colors.appColors.grayLight,
    alignSelf: "center",
    marginTop: Responsive.heightPercentageToDP(1.5),
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingVertical: Responsive.heightPercentageToDP(2),
    borderBottomWidth: 1,
    borderBottomColor: Colors.opacityColors.blackOpacity4,
  },
  modalTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(20),
    color: Colors.appColors.secondary,
  },
  resetBtn: {
    paddingVertical: Responsive.heightPercentageToDP(0.75),
    paddingHorizontal: Responsive.widthPercentageToDP(3.2),
  },
  resetBtnText: {
    fontFamily: Fonts.semiBold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.primary,
  },
  modalScroll: {
    paddingHorizontal: Responsive.widthPercentageToDP(5.3),
    paddingTop: Responsive.heightPercentageToDP(3),
    paddingBottom: Responsive.heightPercentageToDP(15),
  },
  modalSection: {
    marginBottom: Responsive.heightPercentageToDP(3.5),
  },
  modalSectionTitle: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(12),
    color: Colors.appColors.tertiary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Responsive.heightPercentageToDP(1.5),
  },
  dropdownGroup: {
    gap: Responsive.heightPercentageToDP(2),
  },
  dropdownContainer: {
    gap: Responsive.heightPercentageToDP(0.75),
  },
  dropdownTrigger: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Colors.appColors.grayLight,
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
    borderRadius: Responsive.widthPercentageToDP(3.2),
  },
  dropdownText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.secondary,
  },
  dropdownIcon: {
    width: Responsive.widthPercentageToDP(4.3),
    height: Responsive.heightPercentageToDP(2),
    tintColor: Colors.appColors.tertiary,
  },
  rotate270: {
    transform: [{ rotate: "270deg" }],
  },
  rotate90: {
    transform: [{ rotate: "90deg" }],
  },
  dropdownOptions: {
    backgroundColor: Colors.appColors.grayLight,
    borderRadius: Responsive.widthPercentageToDP(3.2),
    marginTop: Responsive.heightPercentageToDP(0.5),
    overflow: "hidden",
  },
  dropdownOption: {
    paddingHorizontal: Responsive.widthPercentageToDP(4.3),
    paddingVertical: Responsive.heightPercentageToDP(1.5),
    borderBottomWidth: 1,
    borderBottomColor: Colors.appColors.borderLight,
  },
  dropdownOptionText: {
    fontFamily: Fonts.regular,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  dropdownOptionTextSelected: {
    fontFamily: Fonts.semiBold,
    color: Colors.appColors.primary,
  },
  checkboxGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Responsive.widthPercentageToDP(3.2),
  },
  checkboxItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: Responsive.widthPercentageToDP(2.7),
    width: "48%",
    backgroundColor: Colors.appColors.grayLight,
    paddingHorizontal: Responsive.widthPercentageToDP(3.2),
    paddingVertical: Responsive.heightPercentageToDP(1.75),
    borderRadius: Responsive.widthPercentageToDP(3.2),
    borderWidth: 1,
    borderColor: "transparent",
  },
  checkboxItemActive: {
    backgroundColor: "rgba(255, 102, 0, 0.08)",
    borderColor: Colors.appColors.primary,
  },
  checkboxBox: {
    width: Responsive.widthPercentageToDP(5.3),
    height: Responsive.heightPercentageToDP(2.5),
    borderRadius: Responsive.widthPercentageToDP(1.6),
    borderWidth: 1.5,
    borderColor: Colors.appColors.bookmarkInactive,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxBoxActive: {
    borderColor: Colors.appColors.primary,
    backgroundColor: Colors.appColors.primary,
  },
  checkMark: {
    color: Colors.appColors.white,
    fontSize: 11,
    fontWeight: "900",
  },
  checkboxText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Responsive.heightPercentageToDP(1.5),
  },
  toggleLabel: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(15),
    color: Colors.appColors.secondary,
  },
  toggleSwitch: {
    width: Responsive.widthPercentageToDP(12.8),
    height: Responsive.heightPercentageToDP(3.25),
    borderRadius: Responsive.widthPercentageToDP(3.5),
    backgroundColor: Colors.appColors.grayLight,
    padding: Responsive.widthPercentageToDP(0.5),
    justifyContent: "center",
  },
  toggleSwitchActive: {
    backgroundColor: Colors.appColors.primary,
  },
  toggleThumb: {
    width: Responsive.widthPercentageToDP(5.8),
    height: Responsive.widthPercentageToDP(5.8),
    borderRadius: Responsive.widthPercentageToDP(2.9),
    backgroundColor: Colors.appColors.white,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.25) },
    shadowOpacity: 0.1,
    shadowRadius: Responsive.widthPercentageToDP(0.5),
    elevation: 2,
  },
  toggleThumbActive: {
    alignSelf: "flex-end",
  },
  toggleThumbInactive: {
    alignSelf: "flex-start",
  },
  sliderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Responsive.heightPercentageToDP(1.5),
  },
  sliderHeaderText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.secondary,
  },
  sliderHeaderRange: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(14),
    color: Colors.appColors.primary,
  },
  sliderTrackContainer: {
    height: Responsive.heightPercentageToDP(3),
    justifyContent: "center",
    position: "relative",
  },
  sliderTrack: {
    height: Responsive.heightPercentageToDP(0.5),
    borderRadius: Responsive.widthPercentageToDP(0.5),
    backgroundColor: Colors.appColors.grayLight,
    position: "relative",
    justifyContent: "center",
  },
  sliderProgress: {
    position: "absolute",
    height: Responsive.heightPercentageToDP(0.5),
    backgroundColor: Colors.appColors.primary,
  },
  sliderThumb: {
    position: "absolute",
    width: Responsive.widthPercentageToDP(5.3),
    height: Responsive.heightPercentageToDP(2.5),
    borderRadius: Responsive.widthPercentageToDP(2.7),
    backgroundColor: Colors.appColors.white,
    borderWidth: 2,
    borderColor: Colors.appColors.primary,
    shadowColor: Colors.appColors.black,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.25) },
    shadowOpacity: 0.1,
    shadowRadius: Responsive.widthPercentageToDP(0.8),
    elevation: 3,
    transform: [{ translateX: -10 }],
  },
  rangeAdjustContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: Responsive.heightPercentageToDP(1.25),
  },
  buttonGroup: {
    flexDirection: "row",
    gap: Responsive.widthPercentageToDP(1.6),
  },
  adjustButton: {
    backgroundColor: Colors.appColors.grayLight,
    width: Responsive.widthPercentageToDP(7.5),
    height: Responsive.heightPercentageToDP(3.5),
    borderRadius: Responsive.widthPercentageToDP(1.6),
    alignItems: "center",
    justifyContent: "center",
  },
  adjustButtonText: {
    fontSize: Responsive.convertFontScale(16),
  },
  modalFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: Responsive.widthPercentageToDP(5.3),
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderTopWidth: 1,
    borderTopColor: Colors.opacityColors.blackOpacity4,
  },
  applyButton: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: Responsive.widthPercentageToDP(4.3),
    height: Responsive.heightPercentageToDP(6.75),
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.appColors.primary,
    shadowOffset: { width: 0, height: Responsive.heightPercentageToDP(0.5) },
    shadowOpacity: 0.2,
    shadowRadius: Responsive.widthPercentageToDP(2.1),
    elevation: 4,
  },
  applyButtonText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(16),
    color: Colors.appColors.white,
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: Colors.appColors.grayLight,
    padding: Responsive.widthPercentageToDP(1.1),
    borderRadius: Responsive.widthPercentageToDP(3.7),
    position: "relative",
  },
  tabButton: {
    flex: 1,
    paddingVertical: Responsive.heightPercentageToDP(1.2),
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    height: Responsive.heightPercentageToDP(4.75),
  },
  tabButtonActive: {
    backgroundColor: Colors.appColors.primary,
    borderRadius: Responsive.widthPercentageToDP(2.7),
  },
  tabButtonText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    textAlign: "center",
  },
  tabButtonTextActive: {
    color: Colors.appColors.white,
    fontWeight: "700",
  },
  badgeContainer: {
    backgroundColor: Colors.appColors.primary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    fontFamily: Fonts.bold,
    fontSize: Responsive.convertFontScale(11),
    color: Colors.appColors.white,
  },
  dropdownSearchInput: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
    color: Colors.appColors.secondary,
    backgroundColor: Colors.appColors.white,
    paddingHorizontal: Responsive.widthPercentageToDP(3.5),
    paddingVertical: Responsive.heightPercentageToDP(1),
    margin: Responsive.widthPercentageToDP(2),
    borderRadius: Responsive.widthPercentageToDP(2.5),
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
  },
  sourcesScrollContent: {
    gap: Responsive.widthPercentageToDP(2),
    paddingVertical: Responsive.heightPercentageToDP(0.5),
  },
  sourceChip: {
    paddingHorizontal: Responsive.widthPercentageToDP(4),
    paddingVertical: Responsive.heightPercentageToDP(1.2),
    borderRadius: Responsive.widthPercentageToDP(5),
    backgroundColor: Colors.appColors.grayLight,
    borderWidth: 1,
    borderColor: Colors.appColors.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  sourceChipActive: {
    backgroundColor: Colors.appColors.primary,
    borderColor: Colors.appColors.primary,
  },
  sourceChipText: {
    fontFamily: Fonts.medium,
    fontSize: Responsive.convertFontScale(13),
  },
  sourceChipTextActive: {
    color: Colors.appColors.white,
    fontFamily: Fonts.bold,
  },
  sourceChipTextInactive: {
    color: Colors.appColors.secondary,
  },
});

export default styles;


